# This is a config for E2B sandbox template.
# You can use template ID (dmowlcbq2qz9r787k2vd) or template name (vybe-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vybe-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("vybe-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vybe-nextjs-test')

team_id = "ab7752bc-2f6f-493c-a0e2-325ea2b315c2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vybe-nextjs-test"
template_id = "dmowlcbq2qz9r787k2vd"
